<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_UserPassword</name>
   <tag></tag>
   <elementGuidId>685c0670-9490-43f4-a7ed-71fcadb2ab0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='UserPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;UserPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9daae778-59e9-4748-b1ee-40bf6549b3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserPassword</value>
      <webElementGuid>ef0919c9-e5ec-4f41-a14f-c6def2c64d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d13cfdbb-71f6-45dc-8393-d4669f5b5992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;row&quot;]/div[@class=&quot;center&quot;]/form[1]/div[@class=&quot;txt_field&quot;]/input[1]</value>
      <webElementGuid>b163938a-b502-4726-8e34-50a9298c5000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='UserPassword']</value>
      <webElementGuid>e110a814-03c1-4420-9e5f-812e391cb37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5261859c-4104-4bc7-b618-f607990fbcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'UserPassword' and @type = 'password']</value>
      <webElementGuid>c635e255-8bd5-488b-b678-276cc0dc0b42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
