<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login as Admin_emailAdressAdmin</name>
   <tag></tag>
   <elementGuidId>1c5024c1-873c-4ea5-9098-d933f5ce9518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='emailAdressAdmin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;emailAdressAdmin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>025ca147-32df-4dc3-ae54-07906e51d88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailAdressAdmin</value>
      <webElementGuid>2e12080a-f0fd-45fd-948d-57d0499b4033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6598f51-f86d-4c62-b7d0-953a5f2fa7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;row&quot;]/div[@class=&quot;center&quot;]/form[1]/div[@class=&quot;txt_field&quot;]/input[1]</value>
      <webElementGuid>9f666953-4679-492e-8cf8-d67c888bc870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='emailAdressAdmin']</value>
      <webElementGuid>4cec1628-d192-495c-890a-e3c98887f07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>74038e43-3aa0-457a-895d-ee4b5ca4e2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'emailAdressAdmin' and @type = 'text']</value>
      <webElementGuid>995fbc21-1a79-422c-86ca-83f23ddc408d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
