<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_AdminPassword</name>
   <tag></tag>
   <elementGuidId>a9928098-282f-45a9-a999-2befe67b6f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='AdminPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;AdminPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59f7c3d6-1d92-4750-9d83-aadaa06175ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AdminPassword</value>
      <webElementGuid>75bb13b1-fa7b-40cf-bf07-9d7e16c7f19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>67680cb8-e6d4-4b46-ab14-95cd2c3e6ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;row&quot;]/div[@class=&quot;center&quot;]/form[1]/div[@class=&quot;txt_field&quot;]/input[1]</value>
      <webElementGuid>75b9bf79-ae2b-4663-b1ff-aba5c036ad8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='AdminPassword']</value>
      <webElementGuid>6f983267-7e71-4fd7-bf07-b58b07bbe11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>85bbf2f2-2d62-4c6e-8fda-911fc7559a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'AdminPassword' and @type = 'password']</value>
      <webElementGuid>b9df4ab2-3551-42b2-adb3-762af43cfced</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
