<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pending</name>
   <tag></tag>
   <elementGuidId>72e428bc-0a26-4ed6-a806-8b2c848e326d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='orders-tbody']/tr[2]/td[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7bbaa2de-6c89-4088-a02d-b1ee6448bf40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>status ${order.status.toLowerCase()}</value>
      <webElementGuid>2f3f3ea2-378f-4030-b54f-347a87306bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pending</value>
      <webElementGuid>00d0c05e-8b24-42b0-bd8e-dbc2648c2c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orders-tbody&quot;)/tr[2]/td[3]/span[@class=&quot;status ${order.status.toLowerCase()}&quot;]</value>
      <webElementGuid>1b7256f3-6362-466b-8444-32e59c7029ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='orders-tbody']/tr[2]/td[3]/span</value>
      <webElementGuid>b240e086-7f31-477b-9720-0f1548b1d8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun Apr 02 2023 20:37:48 GMT+0000 (Coordinated Universal Time)'])[1]/following::span[1]</value>
      <webElementGuid>ec6f7ecc-c7fb-41a0-a03f-ca40647bb8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete'])[1]/following::span[1]</value>
      <webElementGuid>946454a2-9e14-447f-8b98-7c38d08b1f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cook'])[2]/preceding::span[1]</value>
      <webElementGuid>5dcf1819-fbb5-44fc-a53d-50861edc17b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery'])[2]/preceding::span[1]</value>
      <webElementGuid>2ed45dee-e9fa-48cb-b08b-63324cc59f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pending']/parent::*</value>
      <webElementGuid>c54ea09d-190c-4f16-a5e7-b418ad65c94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/span</value>
      <webElementGuid>0ca1d5d5-a3ef-42e4-b799-64f15a4cf4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pending' or . = 'Pending')]</value>
      <webElementGuid>2d8ba505-595f-4808-b89b-e8b984f8dd98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
